
import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;

public class MainFrame extends javax.swing.JFrame {

    NotesPanel notesPanel;
    VaultPanel vaultPanel;

    public MainFrame() {
        vaultPanel = new VaultPanel(this);
        notesPanel = new NotesPanel(this);

        initComponents();

        Parent.removeAll();

        Parent.add(vaultPanel);

        Parent.repaint();
        Parent.revalidate();
    }

    public void setPanel(String name) {
        switch (name) {
            case "Notes":
                Parent.removeAll();

                Parent.add(notesPanel);

                Parent.repaint();
                Parent.revalidate();
                notesPanel.onInit();
                break;
            case "Vault":
                Parent.removeAll();

                Parent.add(notesPanel);

                Parent.repaint();
                Parent.revalidate();
                vaultPanel.onInit();
                break;
            default:
                System.out.println("Panel not chosen");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        Parent = new javax.swing.JPanel();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Memoir");

        Parent.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatArcDarkIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Parent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
